version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py


workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      